#服务端口
server:
  port: 8081
spring:
  #dubbo配置
  dubbo:
    application: manage-web  #dubbo中的服务名称
    protocol:
      name: dubbo   #dubbo中的通讯协名称
    registry:
      address: 192.168.0.19:2181  #zookeeper注册中心 服务注册地址
      protocol: zookeeper  # zookeeper的通讯协议的名称
    base-package: com.atguigu.gmall.manage  # dubbo的服务的扫描路径	例如dubbo中的@Service注解（非spring注解）
    consumer:
      timeout: 60000
      check: false  #服务治理，启动时检查服务提供者是否存在，ture 报错，fales忽略
#日志级别
logging:
  level: debug

