#服务端口
server:
  port: 8071
#jdbc设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall-study?characterEncoding=UTF-8
    username: root
    password: 1234
  #dubbo配置
  dubbo:
    application: manage-service  #dubbo中的服务名称
    protocol:
      name: dubbo   #dubbo中的通讯协名称
    registry:
      address: 192.168.0.19:2181  #zookeeper注册中心 服务注册地址
      protocol: zookeeper  # zookeeper的通讯协议的名称
    base-package: com.atguigu.gmall.manage  # dubbo的服务的扫描路径	例如dubbo中的@Service注解（非spring注解）
    consumer:
      check: false
      timeout: 60000
#mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#日志级别
logging:
  level: debug

